name: GitHub CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
      - uses: actions/checkout@v4
        with:
          path: workspace/src/${{ github.event.repository.name }}
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble
      - run: rosdep update && rosdep install --from-paths src -y --ignore-src --rosdistro humble
        working-directory: workspace
      - run: sudo python3 -m pip install -U pip && sudo python3 -m pip install -r src/${{ github.event.repository.name }}/requirements.txt
        working-directory: workspace
      - run: source /opt/ros/humble/setup.bash && colcon build && source install/setup.bash && colcon test && colcon test-result --all --verbose
        working-directory: workspace
      - run: sudo python3 -m pip install black autoflake
        working-directory: workspace
      - run: black --target-version py310 --check src/${{ github.event.repository.name }}
        working-directory: workspace
      - run: autoflake --recursive --check src/${{ github.event.repository.name }}
        working-directory: workspace
